### ISSUE TITLE
Question  about TTS suport

### ISSUE THREAD

**Issue by The-Mr-L** [kerryeon/rustts#1]
hey thank you  for sharing!. Are you planning to implement TTS as well? :)

**Comment by The-Mr-L** [comment]
oh well, I just saw your last commit now, my bad. you can just close this one . thanks

**Comment by HoKim98** [comment]
Yes, there are plans to eventually finish the TTS implementation of `YourTTS`.

Probably, personally, We plan on implementing it every weekend. We aim to be able to use it after a month.

**Comment by The-Mr-L** [comment]
sounds great!

**Comment by HoKim98** [comment]
I just finished a basic TTS implementation using `YourTTS`. I've uploaded it with model parameters, so you can try it out of the box.

If this is not the feature you want, please reopen this issue.
If you think the topic is a little different, feel free to open another issue!
