### ISSUE TITLE
Running the example uses up all available memory until killed by the system

### ISSUE THREAD

**Issue by knochenhans** [kerryeon/rustts#3]
Hi, when I try to run the example (`cargo run --example tts -- "Hello Mr. my yesterday"`), the process eats up all available memory on my system (~10 GB) and then is killed by system. Is this a bug or do I just don’t have enough RAM? :) I’m on Arch Linux, kernel version 5.16.11, Rust 1.59.

**Comment by HoKim98** [comment]
I never thought about resources, let me check and get some feedback!

**Comment by HoKim98** [comment]
I measured the performance of `TTS example` and below is the results.

* OS: Ubuntu 20.04 LTS (AMD64)
* Processor: AMD EPYC 7502P 32-Core Processor
    * Architecture: amd64; x86_64
* CPU Usage: Consumed Up to 11 processors to the max
* RAM Usage: Consumed **Up to 4GB**
    * Total memory: 128GB
    * Memory allocation of Tensors was managed well by `LibTorch` like GC.
* GPU Usage: N/A (No GPU cards)

In my environment, I couldn't find the reasonable key to solve the problem.
So, can you mind describing more about your environment?

* Processor & Architecture
* Is `LibTorch` installed by manual? (maybe via pacman/AUR)
* GPU

If the information is not sufficient to solve it, then I will append some benchmark stuffs in the example code.

**Comment by knochenhans** [comment]
Sorry, I had lost track of this. Anyway, I just tried this again (after a few system updates in-between, Rust 1.60 among others) and it works fine now.

**Comment by HoKim98** [comment]
Oh, glad to be resolved!

I think there is no more issues, so I'll close it.
